name: pull-request-workflow
on:
  pull_request:
    types: [opened] # pull request가 생성된 시점에만 트리거 발생

jobs:
  pull-request-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello github
          echo github action34
