name: workflow-dispatch
on:
  workflow_dispatch:
    inputs:
      name1: # 어떤 이름이든 사용가능, 다른곳에서 불러 사용 가능
        description: "set name" # UI상 이름
        required: true
        default: "github-actions"
        type: string
      environment2:
        description: "set env"
        required: true
        default: "dev"
        type: choice
        options: # choide타입일 경우에 옵션
          - dev
          - qa
          - prod

jobs:
  workflow-dispatch-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo github action
      - name: echo inputs
        run: |
          echo ${{ inputs.name1}}  
          echo ${{ inputs.environment2}}
