name: create-repo
on:
  workflow_dispatch: # 수동  트리거 설정
    inputs:
      prefix:
        description: "set repo prefix"
        required: true
        default: "service"
        type: choice
        options:
          - example
          - service
      name:
        description: "set repo name"
        required: true
        default: "github-actions"
        type: string

jobs:
  create-repo-automation:
    runs-on: ubuntu-latest
    steps:
      - name: gh auth login
        run: |
          echo ${{ sescrets.PEERSONAM_ACCESS_TOEKN}} | gh auth login --with-token               # github jobs에서 권한 사용할 수 있도록
      - name: create-repo
        run: |
          gh repo create github-action/${{input.prefix}}-${{input.name}} --public --add-readme   # input값으로 repo 생성
