name: var-2
on: push

jobs:
  get-var:
  environment: test
    runs-on: ubuntu-latest
    steps:
      - name: get var
        run: echo ${{vars.level}}
    steps:
      - name: get var
        run: echo ${{vars.level1}}
