name: var-2
on: push

jobs:
  get-var:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: get var1
        run: echo ${{vars.level}}
      - name: get var2
        run: echo ${{vars.level1}}
